---
- name: Deploy stats app
  hosts: cp_nodes
  become: yes
  tasks:    
    - name: Get Kafka external IP and port
      command: "kubectl get service kafka-cluster -o=jsonpath='{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].nodePort}'"
      register: kafka_info

    - name: Set variables from Kafka information
      set_fact:
        kafka_bootstrap_servers: "{{ kafka_info.stdout }}"

    - name: Create TrafficStats directory
      command: sh -c "mkdir -p /tmp/TrafficStats"

    - name: Copier le fichier manifest
      copy:
        src: ../../Manifests/TrafficStats/my-stats-script-deployment.yaml
        dest: /tmp/TrafficStats/my-stats-script-deployment.yaml

    - name: Modifier les paramètres dans le manifest
      replace:
        path: /tmp/TrafficStats/my-stats-script-deployment.yaml
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: 'kafka_bootstrap_servers_value', replace: "{{ kafka_bootstrap_servers }}" }
        - { regexp: 'kafka_topic_value', replace: "visualisation" }
        - { regexp: 'mongo_tcp_uri_value', replace: "mongodb://mongodb-test.default.svc.cluster.local:27017/" }
        - { regexp: 'mongo_udp_uri_value', replace: "mongodb://mongodb-test-1.default.svc.cluster.local:27017/" }
        - { regexp: 'mongo_icmp_uri_value', replace: "mongodb://mongodb-test-2.default.svc.cluster.local:27017/" }
        - { regexp: 'mongo_unknown_uri_value', replace: "mongodb://mongodb-test-3.default.svc.cluster.local:27017/" }

    - name: Apply the Kubernetes configuration for stats-script
      command: kubectl apply -f /tmp/TrafficStats/my-stats-script-deployment.yaml