---
- name: Deploy stats app
  hosts: cp_nodes
  become: yes
  tasks:    
    - name: Get Kafka external IP and port
      command: "kubectl get service kafka-cluster -o=jsonpath='{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].nodePort}'"
      register: kafka_info

    - name: Set variables from Kafka information
      set_fact:
        kafka_bootstrap_servers: "{{ kafka_info.stdout }}"

    - name: Create WebPage directory
      command: sh -c "mkdir -p /tmp/WebPage"

    - name: Copier le fichier manifest
      copy:
        src: ../../Manifests/WebApp/web-page-deployment.yaml
        dest: /tmp/WebPage/web-page-deployment.yaml

    - name: Copier le fichier manifest (service)
      copy:
        src: ../../Manifests/WebApp/web-page-service.yaml
        dest: /tmp/WebPage/web-page-service.yaml

    - name: Modifier les paramètres dans le manifest
      replace:
        path: /tmp/WebPage/web-page-deployment.yaml
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: 'kafka_bootstrap_servers_value', replace: "{{ kafka_bootstrap_servers }}" }
        - { regexp: 'kafka_topic_value', replace: "visualisation" }

    - name: Apply the Kubernetes configuration for web-page-deployment
      command: kubectl apply -f /tmp/WebPage/web-page-deployment.yaml
      
    - name: Apply the Kubernetes configuration for web-page-service
      command: kubectl apply -f /tmp/WebPage/web-page-service.yaml