---
- name: Deploy Apache Zookeeper and Kafka
  become: yes
  hosts: cp_nodes
  tasks:
    - name: Create Zookeeper data directory
      command: sh -c "mkdir -p /bitnami/zookeeper/data"

    - name: Copy the configuration file from local machine to remote master
      copy:
        src: ../../Manifests/Kafka/zookeeper-kafka-cluster.yml
        dest: /tmp/zookeeper-kafka-cluster.yml

    - name: Apply the Kubernetes configuration
      command: kubectl apply -f /tmp/zookeeper-kafka-cluster.yml