kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-3
spec:
  storageClassName: mongodb-storageclass3
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
