apiVersion: v1
kind: Service
metadata:
  name: mongodb-test-1
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27018  # Port que vous souhaitez ajouter
      targetPort: 27018  # Port auquel le service redirigera le trafic

