version: '3'
services:
  my_stats_script:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - MONGO_TCP_URI=${MONGO_TCP_URI}
      - MONGO_UDP_URI=${MONGO_UDP_URI}
      - MONGO_ICMP_URI=${MONGO_ICMP_URI}
      - MONGO_UNKNOWN_URI=${MONGO_UNKNOWN_URI}
    image: ayoubtest1/statsapp:latest

    command: sh -c "python stats-app.py"

