kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-2
spec:
  storageClassName: mongodb-storageclass2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
