apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-page
  name: web-page
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: web-page
  type: LoadBalancer  # Changer le type du service en LoadBalancer
status:
  loadBalancer: {}
