kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-1
spec:
  storageClassName: mongodb-storageclass1
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
