apiVersion: v1
kind: Service
metadata:
  name: mongodb-test-3
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27020  # Port que vous souhaitez ajouter
      targetPort: 27020  # Port auquel le service redirigera le trafic

