apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-test-3
spec:
  serviceName: mongodb-test-3
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb-test-3
    spec:
      containers:
      - name: mongodb-test-3
        image: mongo:4.0.8
        volumeMounts:
        - name: k8-test
          mountPath: /etc/k8-test
          readOnly: true
        - name: mongodb-data
          mountPath: /data/db3
      nodeSelector:
        size: large
      volumes:
      - name: k8-test
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc-3

