apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: my-app
    spec:
      containers:
        - args:
            - sh
            - -c
            - python DataProcessing.py
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka_bootstrap_servers_value
            - name: KAFKA_TOPIC
              value: kafka_topic_value
            - name: MONGO_ICMP_URI
              value: mongo_icmp_uri_value
            - name: MONGO_TCP_URI
              value: mongo_tcp_uri_value
            - name: MONGO_UDP_URI
              value: mongo_udp_uri_value
            - name: MONGO_UNKNOWN_URI
              value: mongo_unknown_uri_value
          image: ayoubtest1/data_processing:latest
          name: my-app
          resources: {}
      restartPolicy: Always
status: {}
